version: '3'
services:
  bpm-initiator:
    build: .
    image: docker.quancy.com.sg/bpm-initiator:${VERSION-latest}
    container_name: bpm-initiator
    network_mode: bridge
    restart: always
    env_file:
      - .env